# Generated by Django 4.1.5 on 2023-05-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlocation', '0002_cat_alter_carinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
